name: Build For Production

on:
  push:
    branches:
      - master

jobs:
  build_for_mac:
    name: Build for Mac
    runs-on: macOS-latest
    steps:
      # Checkout the master branch
      - uses: actions/checkout@master

      # Install node.js
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build and generate a github release draft
      - name: Build and Draft Release
        run: npm run-script release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_LINK: ../.keys/mac-cert.p12
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
